name: unicorndial
description: Floating Action Button with Speed Dial
version: 0.0.1
author: Tiago Martins <tiagojencmartins@gmail.com>
homepage: https://github.com/tiagojencmartins

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">2.0.0-dev.63.0.flutter-4c9689c1d2 <3.0.0"